ARTEMIS-4420 user auth leaks into non-Artemis servlets
apache/activemq-artemis pull request #4897
Opened 2024-04-20 04:38 UTC by jbertram

2024-04-25 17:18 UTC, jbertram commented
@clebertsuconic, let's get this into 2.34.0. Can you review and merge? Thanks!

2024-05-09 14:23 UTC, gtully reviewed
my understanding is the problem is with the filters setting thread locals and not clearing them,  so even if they filters are only on specific contexts, the threads won't respect that, and the data will leak.

2024-05-09 14:29 UTC, gtully commented
Using a thread local to propagate the session subject is fine, but it needs to be scoped to the user of that thread for the request, and cleared on response. so set every time.

2024-05-22 04:19 UTC, jbertram commented
@gtully, point taken. I've updated the PR with what I believe will address the `ThreadLocal` issue. I wasn't able to come up with a way to test it automatically, but manual tests (e.g. the use-case outlined in the Jira) is working fine now.

2024-05-22 09:09 UTC, gtully requested changes

2024-05-22 09:09 UTC, gtully commented on artemis-web/src/main/java/org/apache/activemq/artemis/component/WebServerComponent.java
> +      /*
I would revert this change. 
the metrics call to jmx which is instrumented to audit, with out this filter the audit on metrics will be less informative.
in addition, there are cases where access to metrics will need authentication, especially when there is RBAC on JMX mbeans.

2024-05-22 09:09 UTC, gtully commented on artemis-web/src/main/java/org/apache/activemq/artemis/component/WebServerComponent.java
> +                           AuditLogger.currentCaller.remove();
that looks right

2024-05-22 17:06 UTC, gtully approved these changes
that looks good to me.

2024-05-22 19:10 UTC, merged